### ISSUE TITLE
[BE] 예외 처리 전략을 논의한다

### ISSUE THREAD

**Issue by NewWisdom** [woowacourse-teams/2021-nolto#106]
## 기능 요구 사항
- 프론트엔드와 협의하여 예외 응답 스키마를 논의한다.
- 논의된 내용을 바탕으로 애플리케이션 내에서 적용할 예외 처리 전략을 논의하고 적용한다

**Comment by bosl95** [comment]
<image src='https://user-images.githubusercontent.com/34594339/126620428-29c31931-d604-4d40-b5f8-994163386547.png' width='50%'>

**Comment by bosl95** [comment]
앞으로 생길 예외는 위에 error code 페이지에 exception을 적고 팀원들과 논의하여 계속 적기로 합시다 👏👏👏👏
