### ISSUE TITLE
[BE] 이미지 전송시 용량이 클 경우 CORS가 나는 문제를 해결한다.

### ISSUE THREAD

**Issue by NewWisdom** [woowacourse-teams/2021-nolto#172]
## 기능 요구 사항
- form data  형식의 post요청시 이미지 용량이 크면 cors 문제 발생
- [stackoverflow 글](https://stackoverflow.com/questions/52971336/cors-problem-if-content-type-multipart-form-data)을 참고해 `client_max_body_size` 를 변경한다.

**Comment by PapimonLikelion** [comment]
Nginx의 기본 클라이언트 요청이 1MB로 설정되어 발생한 문제였습니다. 
10MB까지 사용자의 요청을 받을 수 있도록 재설정하였습니다 :) 

![image](https://user-images.githubusercontent.com/61370901/126175603-48b33c7c-3694-4db6-af26-4efc4696892a.png)
