### ISSUE TITLE
[BE] 재배포시 기존 서버의 스레드가 제대로 종료되도록 수정

### ISSUE THREAD

**Issue by bosl95** [woowacourse-teams/2021-nolto#231]
## 기능 요구 사항

- 현재는 `kill -15 ` 이후 sleep을 주어 종료
- 기존 서버의 스레드가 제대로 종료 되지 않고 새로운 서버가 재시작되는 이슈가 있음
- dev 서버는 `kill -9`을 하도록 임시 수정

**Comment by PapimonLikelion** [comment]
![image](https://user-images.githubusercontent.com/61370901/126941877-575ff231-7e2b-4529-bcc3-cad8428bc638.png)

**Comment by bosl95** [comment]
`kill -0`와 while문을 통해 해결
