### ISSUE TITLE
[BE] LocalStack을 통해 AWS S3 이미지 서비스 통합테스트를 수행한다.

### ISSUE THREAD

**Issue by NewWisdom** [woowacourse-teams/2021-nolto#232]
## 기능 요구 사항
- 로컬 환경에서 s3에 접근할 수 없기 때문에 imageService를 테스트할 수 없다. 
- LocalStack을 통해서 s3 관련 이미지 통합 테스트를 수행한다.

### 참고자료 
- [LocalStack을 활용한 Integration Test 환경 만들기](https://techblog.woowahan.com/2638/)

**Comment by bosl95** [comment]
드디어 테스트가 !!!!!!!!!!!!!!!!!!!!!!!!!!!! ✨✨✨✨
