### ISSUE TITLE
[BE] 코드에서 악취 제거하기

### ISSUE THREAD

**Issue by Gomding** [woowacourse-teams/2021-nolto#449]
## 기능 요구 사항
- 소나큐브에서 알려준 코드 악취들 제거하기

![image](https://user-images.githubusercontent.com/57378410/128989844-dbce1177-6d00-4402-ac94-a3da44e1d9e9.png)

**Comment by bosl95** [comment]
![image](https://user-images.githubusercontent.com/34594339/128990188-061ef08d-a271-49c1-9a15-13960b0c59ef.png)

**Comment by NewWisdom** [comment]
냄새나무늬
